--[[
    Generated by Map Editor.

    The map is not put into the world all at once and left there: only the part of it the player is
    anywhere near stands at any moment, and the rest goes out and comes back as they move. See stream().

    Everything here is local to this client. Every player running this resource builds the same map from
    the same map.json, so nothing is replicated and nothing counts against the server's entity budget.
]]

-- How far away the map's props stay drawn, in metres.
local LOD_DISTANCE = 3000

-- How far from the player something may stand before it is taken back out of the world, in metres, or
-- -1 to keep the whole map standing wherever the player is. This is the smart streaming range as it
-- stood in the editor when the map was exported; change it here and the map streams to whatever you
-- change it to.
local STREAMING_RANGE = 500

-- Something comes back a little closer in than it went out, so that an entity sitting exactly on the
-- boundary is not spawned and deleted again on alternate frames as the player shifts their weight.
local RETURN_RATIO = 0.85

-- How much may be spawned and deleted in a single frame. Spawning is the expensive half, so a burst of
-- it is what a player feels as a stutter; deleting is cheap enough to allow more of, and it is what
-- buys back the frame rate.
local SPAWNS_PER_TICK = 6
local DESPAWNS_PER_TICK = 12

-- How many entities are looked at per frame when deciding what has gone out of range. The scan is a
-- rolling one: a large map takes a few frames to notice the player has left, rather than costing every
-- frame.
local SCAN_PER_TICK = 128

-- A ped stands on its feet and a prop hangs from its centre; the editor stores the centre for both.
local PED_GROUND_OFFSET = 1.0

local entries = {}
local markers = {}
local hidden = {}
local pickupHandles = {}
local scanCursor = 1

local function streamingEnabled()
    return STREAMING_RANGE > 0
end

local function vec(t)
    if type(t) ~= 'table' then return vector3(0.0, 0.0, 0.0) end
    return vector3(t[1] + 0.0, t[2] + 0.0, t[3] + 0.0)
end

local function distanceSquared(position)
    local origin = GetEntityCoords(PlayerPedId(), true)
    -- The parentheses are not decoration: ^ binds tighter than the unary # in Lua.
    local distance = #(position - origin)
    return distance * distance
end

local function isTooFar(position)
    if not streamingEnabled() then return false end
    return distanceSquared(position) > STREAMING_RANGE * STREAMING_RANGE
end

local function hasReturned(position)
    if not streamingEnabled() then return true end
    local edge = STREAMING_RANGE * RETURN_RATIO
    return distanceSquared(position) <= edge * edge
end

--- The model, once the game has it. Without `wait` it asks and hands back false, leaving the caller to
--- come back on a later frame; a model the game does not have at all is never asked for twice.
local function requestModel(hash, wait)
    if hash == 0 then return false end
    if HasModelLoaded(hash) then return true end
    if not IsModelInCdimage(hash) or not IsModelValid(hash) then return false end

    RequestModel(hash)
    if not wait then return false end

    local tries = 0
    while not HasModelLoaded(hash) and tries < 200 do
        Wait(0)
        tries = tries + 1
    end
    return HasModelLoaded(hash)
end

local function spawnProp(entry)
    local position = entry.position

    -- A door hangs on its own hinge: it is spawned static so the game does not drop it, and then left
    -- unfrozen so the player can still swing it.
    local dynamic = entry.dynamic and not entry.door
    local frozen = not entry.dynamic and not entry.door

    local handle = CreateObjectNoOffset(entry.hash, position.x, position.y, position.z, false, false,
        dynamic)
    if handle == 0 then return nil end

    if entry.quaternion then
        SetEntityQuaternion(handle, entry.quaternion[1], entry.quaternion[2], entry.quaternion[3],
            entry.quaternion[4])
    else
        SetEntityRotation(handle, entry.rotation.x, entry.rotation.y, entry.rotation.z, 2, true)
    end

    FreezeEntityPosition(handle, frozen)
    return handle
end

local function spawnVehicle(entry)
    local position = entry.position
    local handle = CreateVehicle(entry.hash, position.x, position.y, position.z, entry.rotation.z,
        false, false)
    if handle == 0 then return nil end

    SetVehicleColours(handle, entry.primaryColor or 0, entry.secondaryColor or 0)

    -- The game reports no liveries on a vehicle with no mod kit installed, so one goes on first.
    if entry.livery and entry.livery >= 0 then
        SetVehicleModKit(handle, 0)
        SetVehicleLivery(handle, entry.livery)
    end

    SetVehicleSiren(handle, entry.sirens == true)
    FreezeEntityPosition(handle, not entry.dynamic)
    return handle
end

local function startScenario(ped, scenario)
    if not scenario then return end

    local position = GetEntityCoords(ped, true)
    if scenario == '@walk' then
        TaskUseNearestScenarioToCoord(ped, position.x, position.y, position.z, 100.0, -1)
    elseif scenario == '@warp' then
        TaskUseNearestScenarioToCoordWarp(ped, position.x, position.y, position.z, 100.0, -1)
    elseif scenario == '@wander' then
        TaskWanderStandard(ped, 10.0, 10)
    else
        TaskStartScenarioInPlace(ped, scenario, 0, true)
    end
end

local function spawnPed(entry)
    local position = entry.position
    local handle = CreatePed(4, entry.hash, position.x, position.y, position.z - PED_GROUND_OFFSET,
        entry.rotation.z, false, false)
    if handle == 0 then return nil end

    FreezeEntityPosition(handle, not entry.dynamic)

    if entry.weapon and entry.weapon ~= 0 then
        GiveWeaponToPed(handle, entry.weapon, 999, false, true)
    end

    if entry.drawables then
        for slot = 1, #entry.drawables do
            local texture = entry.textures and entry.textures[slot] or 0
            SetPedComponentVariation(handle, slot - 1, entry.drawables[slot], texture, 0)
        end
    end

    startScenario(handle, entry.scenario)
    return handle
end

--- Puts one object of the map into the world. `streaming` says nobody is waiting for it: it is scenery
--- filling in behind a player walking towards it, so a model that is not in memory yet is asked for and
--- the whole thing left for a later frame.
local function spawn(entry, streaming)
    if not requestModel(entry.hash, not streaming) then return nil end

    local handle
    if entry.kind == 'Prop' then
        handle = spawnProp(entry)
    elseif entry.kind == 'Vehicle' then
        handle = spawnVehicle(entry)
    elseif entry.kind == 'Ped' then
        handle = spawnPed(entry)
    end

    if handle then
        SetEntityLodDist(handle, LOD_DISTANCE)
        -- What stops the game's own streamer from taking the map out again the moment the player walks
        -- away. Which is exactly what this script then does instead, deliberately and reversibly.
        SetEntityAsMissionEntity(handle, true, true)
    end

    SetModelAsNoLongerNeeded(entry.hash)
    return handle
end

--- Keeps the map down to the part of it the player is anywhere near. Walked a slice at a time across
--- frames rather than whole every frame, because asking every entity of the map where it is, on every
--- frame, is the cost this is meant to be saving.
local function stream()
    local total = #entries
    if total == 0 then return end

    local spawnsLeft = SPAWNS_PER_TICK
    local despawnsLeft = DESPAWNS_PER_TICK
    local playerVehicle = GetVehiclePedIsIn(PlayerPedId(), false)

    for _ = 1, math.min(total, SCAN_PER_TICK) do
        if scanCursor > total then scanCursor = 1 end

        local entry = entries[scanCursor]
        scanCursor = scanCursor + 1

        if not entry.gone then
            if not entry.handle then
                -- With streaming off everything belongs in the world, which is what fills the map in.
                if hasReturned(entry.position) then
                    if spawnsLeft <= 0 then return end
                    spawnsLeft = spawnsLeft - 1
                    -- A spawn that comes back empty-handed has asked for its model and is tried again on
                    -- a later pass, once the game has it.
                    entry.handle = spawn(entry, true)
                end
            elseif not DoesEntityExist(entry.handle) then
                -- Deleted by the player or by another resource: these are mission entities, so the game
                -- did not do it, and putting it back would be arguing with whoever did.
                entry.handle = nil
                entry.gone = true
            elseif streamingEnabled() and isTooFar(GetEntityCoords(entry.handle, true)) then
                -- A car deleted out from under whoever is driving it is worth one comparison to rule out.
                if entry.handle ~= playerVehicle then
                    if despawnsLeft <= 0 then return end
                    despawnsLeft = despawnsLeft - 1

                    SetEntityAsMissionEntity(entry.handle, true, true)
                    DeleteEntity(entry.handle)
                    entry.handle = nil
                end
            end
        end
    end
end

--- Markers are not entities: they only exist for the frame they are drawn in.
local function drawMarkers()
    for i = 1, #markers do
        local m = markers[i]
        DrawMarker(m.type, m.position.x, m.position.y, m.position.z, 0.0, 0.0, 0.0,
            m.rotation.x, m.rotation.y, m.rotation.z, m.scale.x, m.scale.y, m.scale.z,
            m.red, m.green, m.blue, m.alpha, m.bob, m.faceCamera, 2, m.rotate, nil, nil, false)
    end
end

--- The game streams its own props back in as the player comes and goes. CREATE_MODEL_HIDE survives that,
--- unlike deleting the prop, which is why the removals are applied once here rather than every frame.
local function applyRemovals()
    for i = 1, #hidden do
        local h = hidden[i]
        CreateModelHide(h.position.x, h.position.y, h.position.z, 1.0, h.hash, false)
    end
end

local function readMap()
    local text = LoadResourceFile(GetCurrentResourceName(), 'map.json')
    if not text then
        print('^1[map] map.json is missing from this resource.^7')
        return false
    end

    local ok, document = pcall(json.decode, text)
    if not ok or type(document) ~= 'table' then
        print('^1[map] map.json could not be read.^7')
        return false
    end

    for _, o in ipairs(document.objects or {}) do
        if o.type == 'Pickup' then
            -- A pickup is not an entity and the game keeps it out of the entity budget: it has a range of
            -- its own, so it is put in once and left to it rather than streamed.
            local p = vec(o.position)
            local handle = CreatePickupRotate(o.hash, p.x, p.y, p.z, 0.0, 0.0,
                vec(o.rotation).z, o.flag or 515, o.amount or 0, 0, false, 0)
            if handle ~= 0 then pickupHandles[#pickupHandles + 1] = handle end
        elseif o.type == 'Prop' or o.type == 'Vehicle' or o.type == 'Ped' then
            entries[#entries + 1] = {
                kind = o.type,
                hash = o.hash,
                position = vec(o.position),
                rotation = vec(o.rotation),
                quaternion = o.quaternion,
                dynamic = o.dynamic == true,
                door = o.door == true,
                weapon = o.weaponHash,
                drawables = o.drawables,
                textures = o.textures,
                scenario = o.scenario,
                primaryColor = o.primaryColor,
                secondaryColor = o.secondaryColor,
                livery = o.livery,
                sirens = o.sirens,
            }
        end
    end

    for _, o in ipairs(document.removeFromWorld or {}) do
        hidden[#hidden + 1] = { hash = o.hash, position = vec(o.position) }
    end

    for _, m in ipairs(document.markers or {}) do
        markers[#markers + 1] = {
            type = m.type or 0,
            position = vec(m.position),
            rotation = vec(m.rotation),
            scale = vec(m.scale),
            red = m.red or 255,
            green = m.green or 255,
            blue = m.blue or 255,
            alpha = m.alpha or 255,
            bob = m.bobUpAndDown == true,
            faceCamera = m.rotateToCamera == true,
            rotate = false,
        }
    end

    return true
end

--- The part of the map the player starts inside goes in in one go, waiting for its models: the map is
--- expected to be standing by the time they can see it. Everything further out is left to stream() to
--- fill in as they walk towards it.
local function spawnNearby()
    for i = 1, #entries do
        local entry = entries[i]
        if hasReturned(entry.position) then
            entry.handle = spawn(entry, false)
        end
    end
end

Citizen.CreateThread(function()
    if not readMap() then return end

    while not NetworkIsSessionStarted() do Wait(100) end
    Wait(500)

    applyRemovals()
    spawnNearby()

    while true do
        Wait(0)
        stream()
        drawMarkers()
    end
end)

--- The map belongs to this resource, so it leaves with it: without this a restart would stack a second
--- copy of every prop on top of the first.
AddEventHandler('onResourceStop', function(resource)
    if resource ~= GetCurrentResourceName() then return end

    for i = 1, #entries do
        local entry = entries[i]
        if entry.handle and DoesEntityExist(entry.handle) then
            SetEntityAsMissionEntity(entry.handle, true, true)
            DeleteEntity(entry.handle)
        end
    end

    for i = 1, #pickupHandles do
        RemovePickup(pickupHandles[i])
    end

    for i = 1, #hidden do
        local h = hidden[i]
        RemoveModelHide(h.position.x, h.position.y, h.position.z, 1.0, h.hash, false)
    end
end)
