--[[
    Generated by Map Editor.

    The map is not put into the world all at once and left there: only the part of it the player is
    anywhere near stands at any moment, and the rest goes out and comes back as they move. See stream().

    Everything here is local to this client. Every player running this resource builds the same map from
    the same map.json, so nothing is replicated and nothing counts against the server's entity budget.
]]

-- How far away the map's props stay drawn, in metres.
local LOD_DISTANCE = 3000

-- How far from the player something may stand before it is taken back out of the world, in metres, or
-- -1 to keep the whole map standing wherever the player is. This is the smart streaming range as it
-- stood in the editor when the map was exported; change it here and the map streams to whatever you
-- change it to.
local STREAMING_RANGE = 500

-- Something comes back a little closer in than it went out, so that an entity sitting exactly on the
-- boundary is not spawned and deleted again on alternate frames as the player shifts their weight.
local RETURN_RATIO = 0.85

-- How much may be spawned and deleted in a single frame. Spawning is the expensive half, so a burst of
-- it is what a player feels as a stutter; deleting is cheap enough to allow more of, and it is what
-- buys back the frame rate.
local SPAWNS_PER_TICK = 6
local DESPAWNS_PER_TICK = 12

-- How many entities are looked at per frame when deciding what has gone out of range. The scan is a
-- rolling one: a large map takes a few frames to notice the player has left, rather than costing every
-- frame.
local SCAN_PER_TICK = 128

-- A ped stands on its feet and a prop hangs from its centre; the editor stores the centre for both.
local PED_GROUND_OFFSET = 1.0

-- How many laser beams may be drawn in one frame, across every laser of the map. A ceiling rather than a
-- budget: sixty overlapping lasers in one room is a mistake, and the frame it costs should be spent
-- finding that out.
local LASER_MAX_BEAMS = 400

-- The multiplayer dictionary the game's own laser beams are textured from.
local BEAM_DICT = 'mpinvperscommon'
local BEAM_CORE = 'beam_middle'
local BEAM_GLOW = 'beam_glow_tapered'

local entries = {}
local markers = {}
local lasers = {}
local hidden = {}
local scanCursor = 1

local function streamingEnabled()
    return STREAMING_RANGE > 0
end

local function vec(t)
    if type(t) ~= 'table' then return vector3(0.0, 0.0, 0.0) end
    return vector3(t[1] + 0.0, t[2] + 0.0, t[3] + 0.0)
end

local function distanceSquared(position)
    local origin = GetEntityCoords(PlayerPedId(), true)
    -- The parentheses are not decoration: ^ binds tighter than the unary # in Lua.
    local distance = #(position - origin)
    return distance * distance
end

local function isTooFar(position)
    if not streamingEnabled() then return false end
    return distanceSquared(position) > STREAMING_RANGE * STREAMING_RANGE
end

local function hasReturned(position)
    if not streamingEnabled() then return true end
    local edge = STREAMING_RANGE * RETURN_RATIO
    return distanceSquared(position) <= edge * edge
end

--- The model, once the game has it. Without `wait` it asks and hands back false, leaving the caller to
--- come back on a later frame; a model the game does not have at all is never asked for twice.
local function requestModel(hash, wait)
    if hash == 0 then return false end
    if HasModelLoaded(hash) then return true end
    if not IsModelInCdimage(hash) or not IsModelValid(hash) then return false end

    RequestModel(hash)
    if not wait then return false end

    local tries = 0
    while not HasModelLoaded(hash) and tries < 200 do
        Wait(0)
        tries = tries + 1
    end
    return HasModelLoaded(hash)
end

local function spawnProp(entry)
    local position = entry.position

    -- A door hangs on its own hinge: it is spawned static so the game does not drop it, and then left
    -- unfrozen so the player can still swing it.
    local dynamic = entry.dynamic and not entry.door
    local frozen = not entry.dynamic and not entry.door

    local handle = CreateObjectNoOffset(entry.hash, position.x, position.y, position.z, false, false,
        dynamic)
    if handle == 0 then return nil end

    if entry.quaternion then
        SetEntityQuaternion(handle, entry.quaternion[1], entry.quaternion[2], entry.quaternion[3],
            entry.quaternion[4])
    else
        SetEntityRotation(handle, entry.rotation.x, entry.rotation.y, entry.rotation.z, 2, true)
    end

    FreezeEntityPosition(handle, frozen)
    return handle
end

local function spawnVehicle(entry)
    local position = entry.position
    local handle = CreateVehicle(entry.hash, position.x, position.y, position.z, entry.rotation.z,
        false, false)
    if handle == 0 then return nil end

    SetVehicleColours(handle, entry.primaryColor or 0, entry.secondaryColor or 0)

    -- A livery lives either in the vehicle's own slot or, on everything added since, in mod slot 48,
    -- where SetVehicleLivery cannot reach it. No mod kit, no mods reported at all, so one goes on first.
    if entry.livery and entry.livery >= 0 then
        SetVehicleModKit(handle, 0)
        if GetNumVehicleMods(handle, 48) > 0 then
            SetVehicleMod(handle, 48, entry.livery, false)
        else
            SetVehicleLivery(handle, entry.livery)
        end
    end

    SetVehicleSiren(handle, entry.sirens == true)
    FreezeEntityPosition(handle, not entry.dynamic)
    return handle
end

local function startScenario(ped, scenario)
    if not scenario then return end

    local position = GetEntityCoords(ped, true)
    if scenario == '@walk' then
        TaskUseNearestScenarioToCoord(ped, position.x, position.y, position.z, 100.0, -1)
    elseif scenario == '@warp' then
        TaskUseNearestScenarioToCoordWarp(ped, position.x, position.y, position.z, 100.0, -1)
    elseif scenario == '@wander' then
        TaskWanderStandard(ped, 10.0, 10)
    else
        TaskStartScenarioInPlace(ped, scenario, 0, true)
    end
end

local function spawnPed(entry)
    local position = entry.position
    local handle = CreatePed(4, entry.hash, position.x, position.y, position.z - PED_GROUND_OFFSET,
        entry.rotation.z, false, false)
    if handle == 0 then return nil end

    FreezeEntityPosition(handle, not entry.dynamic)

    if entry.weapon and entry.weapon ~= 0 then
        GiveWeaponToPed(handle, entry.weapon, 999, false, true)
    end

    if entry.drawables then
        for slot = 1, #entry.drawables do
            local texture = entry.textures and entry.textures[slot] or 0
            SetPedComponentVariation(handle, slot - 1, entry.drawables[slot], texture, 0)
        end
    end

    startScenario(handle, entry.scenario)
    return handle
end

--- Puts one object of the map into the world. `streaming` says nobody is waiting for it: it is scenery
--- filling in behind a player walking towards it, so a model that is not in memory yet is asked for and
--- the whole thing left for a later frame.
local function spawn(entry, streaming)
    if not requestModel(entry.hash, not streaming) then return nil end

    local handle
    if entry.kind == 'Prop' then
        handle = spawnProp(entry)
    elseif entry.kind == 'Vehicle' then
        handle = spawnVehicle(entry)
    elseif entry.kind == 'Ped' then
        handle = spawnPed(entry)
    end

    if handle then
        SetEntityLodDist(handle, LOD_DISTANCE)
        -- What stops the game's own streamer from taking the map out again the moment the player walks
        -- away. Which is exactly what this script then does instead, deliberately and reversibly.
        SetEntityAsMissionEntity(handle, true, true)
    end

    SetModelAsNoLongerNeeded(entry.hash)
    return handle
end

--- Keeps the map down to the part of it the player is anywhere near. Walked a slice at a time across
--- frames rather than whole every frame, because asking every entity of the map where it is, on every
--- frame, is the cost this is meant to be saving.
local function stream()
    local total = #entries
    if total == 0 then return end

    local spawnsLeft = SPAWNS_PER_TICK
    local despawnsLeft = DESPAWNS_PER_TICK
    local playerVehicle = GetVehiclePedIsIn(PlayerPedId(), false)

    for _ = 1, math.min(total, SCAN_PER_TICK) do
        if scanCursor > total then scanCursor = 1 end

        local entry = entries[scanCursor]
        scanCursor = scanCursor + 1

        if not entry.gone then
            if not entry.handle then
                -- With streaming off everything belongs in the world, which is what fills the map in.
                if hasReturned(entry.position) then
                    if spawnsLeft <= 0 then return end
                    spawnsLeft = spawnsLeft - 1
                    -- A spawn that comes back empty-handed has asked for its model and is tried again on
                    -- a later pass, once the game has it.
                    entry.handle = spawn(entry, true)
                end
            elseif not DoesEntityExist(entry.handle) then
                -- Deleted by the player or by another resource: these are mission entities, so the game
                -- did not do it, and putting it back would be arguing with whoever did.
                entry.handle = nil
                entry.gone = true
            elseif streamingEnabled() and isTooFar(GetEntityCoords(entry.handle, true)) then
                -- A car deleted out from under whoever is driving it is worth one comparison to rule out.
                if entry.handle ~= playerVehicle then
                    if despawnsLeft <= 0 then return end
                    despawnsLeft = despawnsLeft - 1

                    SetEntityAsMissionEntity(entry.handle, true, true)
                    DeleteEntity(entry.handle)
                    entry.handle = nil
                end
            end
        end
    end
end

--- Markers are not entities: they only exist for the frame they are drawn in.
local function drawMarkers()
    for i = 1, #markers do
        local m = markers[i]
        DrawMarker(m.type, m.position.x, m.position.y, m.position.z, 0.0, 0.0, 0.0,
            m.rotation.x, m.rotation.y, m.rotation.z, m.scale.x, m.scale.y, m.scale.z,
            m.red, m.green, m.blue, m.alpha, m.bob, m.faceCamera, 2, m.rotate, nil, nil, false)
    end
end

--[[
    Lasers.

    Neither are these entities: a laser is the row of numbers the editor saved, and the beams are rebuilt
    from it on every frame. What follows is the same arithmetic Client/LaserRenderer.cs does, which is
    itself the game's own fmmc_lasers.c behind a smaller surface — and it is written out a second time here
    for the same reason drawMarkers is: an exported map runs with nothing but FiveM underneath it, so there
    is no Map Editor to ask. Change one of the two and the other has to follow, or a map will look different
    exported from how it looked in the editor it was built in.

    The clock is the game's, not the resource's: every client of a server reads GetGameTimer within a frame
    of every other, so a blinking laser blinks together for everybody without a single byte being sent.
]]

local function laserDensity(name)
    if name == 'Sparse' then return 0.45, 1.6, 0.5 end
    if name == 'Low' then return 0.7, 1.25, 0.75 end
    if name == 'High' then return 1.4, 0.8, 1.3 end
    if name == 'Maximum' then return 2.0, 0.55, 1.6 end
    return 1.0, 1.0, 1.0
end

local function normalize(v)
    local length = #v
    if length < 0.00001 then return vector3(0.0, 0.0, 0.0) end
    return v / length
end

local function cross(a, b)
    return vector3(a.y * b.z - a.z * b.y, a.z * b.x - a.x * b.z, a.x * b.y - a.y * b.x)
end

--- The three axes a laser's pattern is laid out along, from its pitch/roll/yaw.
local function laserAxes(l)
    local z, x = math.rad(l.rotation.z), math.rad(l.rotation.x)
    local flatten = math.abs(math.cos(x))
    local forward = normalize(vector3(-math.sin(z) * flatten, math.cos(z) * flatten, math.sin(x)))
    if #forward < 0.00001 then forward = vector3(0.0, 1.0, 0.0) end

    local flat = normalize(cross(forward, vector3(0.0, 0.0, 1.0)))
    if #flat < 0.00001 then flat = vector3(1.0, 0.0, 0.0) end
    local perp = cross(flat, forward)

    local roll = math.rad(l.rotation.y)
    local c, s = math.cos(roll), math.sin(roll)
    return forward, flat * c + perp * s, perp * c - flat * s
end

local function laserBeamCount(l)
    if l.pattern == 'Single' then return 1 end
    local countScale = laserDensity(l.density)
    local count = math.ceil(math.max(1, l.beamCount) * countScale)
    if count < 1 then count = 1 end
    if count > LASER_MAX_BEAMS then count = LASER_MAX_BEAMS end
    return count
end

--- Whether beam `index` is lit at `time`. Steady, Blink and Chase; the rhythm runs along the beams of one
--- laser rather than across several, which is what makes Chase a gap somebody can time their way through.
local function laserLit(l, index, time)
    if l.rhythm == 'Blink' then
        local on = math.max(0.0, l.onSeconds)
        local period = on + math.max(0.0, l.offSeconds)
        if period <= 0.0001 then return true end
        return time % period < on
    end

    if l.rhythm == 'Chase' then
        local period = math.max(0.0001, l.chasePeriod)
        local count = math.max(1, laserBeamCount(l))
        local fraction = math.min(1.0, math.max(0.0, l.chaseOnFraction))
        return (time / period + index / count) % 1.0 < fraction
    end

    return true
end

--- This frame's beams for one laser, as { s = start, e = end, i = index } — centred on its position, so a
--- laser turns and moves about the middle of itself.
local function laserBeams(l, time)
    local forward, right, up = laserAxes(l)
    local count = laserBeamCount(l)
    local _, spacing = laserDensity(l.density)
    local length = math.max(0.05, l.beamLength)
    local half = forward * (length * 0.5)
    local out = {}

    if l.pattern == 'Single' then
        out[1] = { s = l.position - half, e = l.position + half, i = 0 }
        return out
    end

    if l.pattern == 'Wall' then
        local height = math.max(0.0, l.height) * spacing
        local step = count > 1 and height / (count - 1) or 0.0
        local first = l.position - up * (height * 0.5)
        local run = right * (length * 0.5)
        for i = 1, count do
            local centre = first + up * (step * (i - 1))
            out[i] = { s = centre - run, e = centre + run, i = i - 1 }
        end
        return out
    end

    local width = math.max(0.0, l.width) * spacing
    local step = count > 1 and width / (count - 1) or 0.0
    local first = l.position - right * (width * 0.5)

    if l.pattern == 'Wave' then
        local phase = time * l.speed
        for i = 1, count do
            local along = step * (i - 1)
            local swing = l.amplitude * math.sin((along + phase) * l.frequency)
            local centre = first + right * along + up * swing
            out[i] = { s = centre - half, e = centre + half, i = i - 1 }
        end
        return out
    end

    -- Grid.
    for i = 1, count do
        local centre = first + right * (step * (i - 1))
        out[i] = { s = centre - half, e = centre + half, i = i - 1 }
    end
    return out
end

local function whiten(channel)
    return math.min(255, channel + 160)
end

--[[
    Six of the natives the beams are drawn with have no name in this runtime's list, so they are called by
    hash — the same six, and for the same reason, as in Client/LaserRenderer.cs. A hash a future game build
    moves would otherwise throw on every beam of every frame, so each group is tried, switched off on its
    first failure, and said once in the console. A laser with its glow switched off is still a laser.
]]
local DRAW_SPRITE_POLY = 0x29280002282F1928
local DRAW_CAPSULE_LIGHT = 0x330F4FA20FB57738
local DRAW_MARKER_GLOW = 0xE59B0A106CC15FC2
local SET_BLEND_STATE_ADDITIVE = 0x01677A72A8BDCD1A
local SET_BLEND_STATE_NORMAL = 0x976D155439608592
local GENERATE_PED_DAMAGE_EVENT = 0x6D1FCD0950EFA3DD

local glowsOk, texturedOk, blendOk, damageEventOk = true, true, true, true

--- Calls a native by hash and reports whether it worked. `flag` names the group in the message.
local function tryNative(flag, what, hash, ...)
    if not flag then return false end
    local ok, err = pcall(Citizen.InvokeNative, hash, ...)
    if not ok then
        print(('^3[map] the %s native is unavailable (%s); lasers carry on without it.^7'):format(what, err))
    end
    return ok
end

--- One beam-body quad, as two triangles drawn from both sides: the billboard is computed rather than asked
--- of the game, so which face ends up towards the eye is not promised.
local function laserQuad(mid, along, across, halfLen, halfWidth, r, g, b, a, texture)
    local l = along * halfLen
    local w = across * halfWidth
    local v0, v3, v6, v9 = mid - w + l, mid + w + l, mid - w - l, mid + w - l
    local order = { v3, v0, v9, v6, v9, v0, v9, v0, v3, v0, v9, v6 }

    for i = 1, 12, 3 do
        local p1, p2, p3 = order[i], order[i + 1], order[i + 2]
        if texture and texturedOk then
            texturedOk = tryNative(texturedOk, 'textured polygon', DRAW_SPRITE_POLY,
                p1.x, p1.y, p1.z, p2.x, p2.y, p2.z, p3.x, p3.y, p3.z,
                r, g, b, a, BEAM_DICT, texture, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0)
        else
            DrawPoly(p1.x, p1.y, p1.z, p2.x, p2.y, p2.z, p3.x, p3.y, p3.z, r, g, b, a)
        end
    end
end

--- One beam, in the four layers the game's own laser grid draws it in: a capsule light along its length, a
--- glowing dot at each end, a soft tapered-glow ribbon and a bright core ribbon.
local function drawBeam(l, beam, camera, textured)
    local delta = beam.e - beam.s
    local length = #delta
    if length < 0.0001 then return end

    local dir = delta / length
    local mid = (beam.s + beam.e) * 0.5
    local r, g, b, a = l.red, l.green, l.blue, l.alpha

    if glowsOk then
        local head, tail = beam.s + dir * 0.05, beam.e - dir * 0.05
        glowsOk = tryNative(glowsOk, 'capsule light', DRAW_CAPSULE_LIGHT,
            mid.x, mid.y, mid.z, dir.x, dir.y, dir.z, r, g, b,
            1.0, 6.0, math.max(0.05, length - 0.05), 250.0)
        glowsOk = tryNative(glowsOk, 'marker glow', DRAW_MARKER_GLOW,
            head.x, head.y, head.z, 0.116, r, g, b, 0.9)
        glowsOk = tryNative(glowsOk, 'marker glow', DRAW_MARKER_GLOW,
            tail.x, tail.y, tail.z, 0.116, r, g, b, 0.9)
    end

    local toCam = camera - mid
    if #toCam < 0.0001 then toCam = vector3(0.0, 0.0, 1.0) end
    local across = normalize(cross(dir, normalize(toCam)))
    if #across < 0.00001 then across = normalize(cross(dir, vector3(0.0, 0.0, 1.0))) end
    if #across < 0.00001 then return end

    local thickness = math.max(0.001, l.thickness)
    local halfLen = length * 0.5

    if textured and texturedOk then
        laserQuad(mid, dir, across, halfLen + 0.1, thickness * 1.7, r, g, b, a, BEAM_GLOW)
        laserQuad(mid, dir, across, halfLen + 0.1, thickness, whiten(r), whiten(g), whiten(b), a, BEAM_CORE)
    else
        laserQuad(mid, dir, across, halfLen, thickness * 1.6, r, g, b, math.min(a, 200), nil)
        laserQuad(mid, dir, across, halfLen, thickness * 0.5, whiten(r), whiten(g), whiten(b), a, nil)
    end
end

--- The shortest distance between two segments, and where on the first it is measured from. The narrow
--- phase: the first segment is the beam, the second the line down the middle of the ped.
local function segmentDistance(p1, q1, p2, q2)
    local d1, d2, r = q1 - p1, q2 - p2, p1 - p2
    local a, e, f = #(d1) * #(d1), #(d2) * #(d2), d2.x * r.x + d2.y * r.y + d2.z * r.z
    local s, t = 0.0, 0.0

    if a <= 0.000001 and e <= 0.000001 then return #(p1 - p2), p1 end

    if a <= 0.000001 then
        t = math.min(1.0, math.max(0.0, f / e))
    else
        local c = d1.x * r.x + d1.y * r.y + d1.z * r.z
        if e <= 0.000001 then
            s = math.min(1.0, math.max(0.0, -c / a))
        else
            local b = d1.x * d2.x + d1.y * d2.y + d1.z * d2.z
            local denom = a * e - b * b
            if denom > 0.000001 then s = math.min(1.0, math.max(0.0, (b * f - c * e) / denom)) end
            t = (b * s + f) / e
            if t < 0.0 then
                t = 0.0
                s = math.min(1.0, math.max(0.0, -c / a))
            elseif t > 1.0 then
                t = 1.0
                s = math.min(1.0, math.max(0.0, (b - c) / a))
            end
        end
    end

    local onFirst = p1 + d1 * s
    return #(onFirst - (p2 + d2 * t)), onFirst
end

--- Whether something solid stands between the emitter and the point the beam met the player. One probe for
--- the whole laser: a crate that hides them from the nearest beam hides them from its neighbours too.
local function laserBlocked(from, to, ped)
    local handle = StartExpensiveSynchronousShapeTestLosProbe(
        from.x, from.y, from.z, to.x, to.y, to.z, 1 + 16 + 32, ped, 7)
    local status, hit = GetShapeTestResult(handle)
    return status == 2 and hit
end

local laserLastStamp = 0

local function drawLasers()
    if #lasers == 0 then return end

    local now = GetGameTimer()
    local elapsed = laserLastStamp == 0 and 0 or (now - laserLastStamp)
    laserLastStamp = now
    local frameSeconds = elapsed <= 0 and 0.0 or math.min(0.25, elapsed / 1000.0)

    local time = now / 1000.0
    local ped = PlayerPedId()
    local alive = ped ~= 0 and not IsEntityDead(ped)
    local here = GetEntityCoords(ped, true)
    local camera = GetFinalRenderedCamCoord()
    local drawn = 0

    if not HasStreamedTextureDictLoaded(BEAM_DICT) then RequestStreamedTextureDict(BEAM_DICT, false) end
    local ready = HasStreamedTextureDictLoaded(BEAM_DICT)

    -- Additive while the beams are drawn, normal again afterwards: overlapping beams have to brighten, and
    -- the blend state is the game's rather than this resource's. Switched on by the first beam rather than
    -- at the top, so that a map whose lasers are all on the other side of town brackets nothing.
    local blendOn = false

    for i = 1, #lasers do
        local l = lasers[i]

        if drawn < LASER_MAX_BEAMS and
            (l.activationRange <= 0.0 or #(here - l.position) <= l.activationRange) then

            local low, high = here + vector3(0.0, 0.0, 0.3), here + vector3(0.0, 0.0, 1.6)
            local beams = laserBeams(l, time)
            local burning, hitPoint, hitFrom = 0, nil, nil
            local radius = math.max(0.01, l.hitRadius)

            for b = 1, #beams do
                if drawn >= LASER_MAX_BEAMS then break end
                local beam = beams[b]

                if laserLit(l, beam.i, time) then
                    if not blendOn then
                        blendOn = true
                        blendOk = tryNative(blendOk, 'additive blend state', SET_BLEND_STATE_ADDITIVE)
                    end

                    drawBeam(l, beam, camera, l.textured and ready)
                    drawn = drawn + 1

                    if alive then
                        local gap, onBeam = segmentDistance(beam.s, beam.e, low, high)
                        if gap <= radius then
                            burning = burning + 1
                            if not hitPoint then hitPoint, hitFrom = onBeam, beam.s end
                        end
                    end
                end
            end

            if hitPoint and alive and not laserBlocked(hitFrom, hitPoint, ped) then
                if l.dealsDamage then
                    local _, _, damageScale = laserDensity(l.density)
                    l.debt = (l.debt or 0.0) + l.damagePerSecond * damageScale * burning * frameSeconds

                    if damageEventOk and not IsPedRagdoll(ped) then
                        damageEventOk = tryNative(damageEventOk, 'ped damage event', GENERATE_PED_DAMAGE_EVENT,
                            ped, hitPoint.x, hitPoint.y, hitPoint.z, GetHashKey('WEAPON_PISTOL'))
                    end

                    local whole = math.floor(l.debt)
                    if whole > 0 then
                        l.debt = l.debt - whole
                        ApplyDamageToPed(ped, whole, true, 0)
                        if IsEntityDead(ped) then StartEntityFire(ped) end
                    end
                else
                    l.debt = 0.0
                end
            else
                l.debt = 0.0
            end
        else
            l.debt = 0.0
        end
    end

    if blendOn then blendOk = tryNative(blendOk, 'normal blend state', SET_BLEND_STATE_NORMAL) end
end

--- The game streams its own props back in as the player comes and goes. CREATE_MODEL_HIDE survives that,
--- unlike deleting the prop, which is why the removals are applied once here rather than every frame.
local function applyRemovals()
    for i = 1, #hidden do
        local h = hidden[i]
        CreateModelHide(h.position.x, h.position.y, h.position.z, 1.0, h.hash, false)
    end
end

local function readMap()
    local text = LoadResourceFile(GetCurrentResourceName(), 'map.json')
    if not text then
        print('^1[map] map.json is missing from this resource.^7')
        return false
    end

    local ok, document = pcall(json.decode, text)
    if not ok or type(document) ~= 'table' then
        print('^1[map] map.json could not be read.^7')
        return false
    end

    for _, o in ipairs(document.objects or {}) do
        if o.type == 'Prop' or o.type == 'Vehicle' or o.type == 'Ped' then
            entries[#entries + 1] = {
                kind = o.type,
                hash = o.hash,
                position = vec(o.position),
                rotation = vec(o.rotation),
                quaternion = o.quaternion,
                dynamic = o.dynamic == true,
                door = o.door == true,
                weapon = o.weaponHash,
                drawables = o.drawables,
                textures = o.textures,
                scenario = o.scenario,
                primaryColor = o.primaryColor,
                secondaryColor = o.secondaryColor,
                livery = o.livery,
                sirens = o.sirens,
            }
        end
    end

    for _, o in ipairs(document.removeFromWorld or {}) do
        hidden[#hidden + 1] = { hash = o.hash, position = vec(o.position) }
    end

    for _, m in ipairs(document.markers or {}) do
        markers[#markers + 1] = {
            type = m.type or 0,
            position = vec(m.position),
            rotation = vec(m.rotation),
            scale = vec(m.scale),
            red = m.red or 255,
            green = m.green or 255,
            blue = m.blue or 255,
            alpha = m.alpha or 255,
            bob = m.bobUpAndDown == true,
            faceCamera = m.rotateToCamera == true,
            rotate = false,
        }
    end

    -- Every default here is the one the editor's own Laser carries, so a map written by a later editor that
    -- has one more knob still runs, with the knob it does not know about at something sensible.
    --
    -- The counts and colours go through math.floor and the sizes through +0.0 rather than being taken as
    -- they come: json.decode hands back whichever numeric subtype the text happened to look like, and the
    -- native invoker picks int or float from that subtype. A colour that arrived as 255.0 would be pushed
    -- as a float into a parameter the native reads as an integer.
    for _, l in ipairs(document.lasers or {}) do
        lasers[#lasers + 1] = {
            pattern = l.pattern or 'Grid',
            position = vec(l.position),
            rotation = vec(l.rotation),
            beamLength = (l.beamLength or 8.0) + 0.0,
            width = (l.width or 6.0) + 0.0,
            height = (l.height or 3.0) + 0.0,
            beamCount = math.floor(l.beamCount or 8),
            density = l.density or 'Medium',
            thickness = (l.thickness or 0.03) + 0.0,
            red = math.floor(l.red or 255),
            green = math.floor(l.green or 40),
            blue = math.floor(l.blue or 40),
            alpha = math.floor(l.alpha or 255),
            textured = l.textured ~= false,
            rhythm = l.rhythm or 'Steady',
            onSeconds = l.onSeconds or 1.5,
            offSeconds = l.offSeconds or 0.5,
            chasePeriod = l.chasePeriod or 3.0,
            chaseOnFraction = l.chaseOnFraction or 0.5,
            amplitude = l.amplitude or 1.5,
            frequency = l.frequency or 0.6,
            speed = l.speed or 1.0,
            dealsDamage = l.dealsDamage ~= false,
            damagePerSecond = l.damagePerSecond or 250.0,
            activationRange = l.activationRange or 60.0,
            hitRadius = l.hitRadius or 0.35,
            debt = 0.0,
        }
    end

    return true
end

--- The part of the map the player starts inside goes in in one go, waiting for its models: the map is
--- expected to be standing by the time they can see it. Everything further out is left to stream() to
--- fill in as they walk towards it.
local function spawnNearby()
    for i = 1, #entries do
        local entry = entries[i]
        if hasReturned(entry.position) then
            entry.handle = spawn(entry, false)
        end
    end
end

Citizen.CreateThread(function()
    if not readMap() then return end

    while not NetworkIsSessionStarted() do Wait(100) end
    Wait(500)

    applyRemovals()
    spawnNearby()

    while true do
        Wait(0)
        stream()
        drawMarkers()
        drawLasers()
    end
end)

--- The map belongs to this resource, so it leaves with it: without this a restart would stack a second
--- copy of every prop on top of the first.
AddEventHandler('onResourceStop', function(resource)
    if resource ~= GetCurrentResourceName() then return end

    for i = 1, #entries do
        local entry = entries[i]
        if entry.handle and DoesEntityExist(entry.handle) then
            SetEntityAsMissionEntity(entry.handle, true, true)
            DeleteEntity(entry.handle)
        end
    end

    -- Nothing to take down for the markers or the lasers: neither is in the world between frames.
    for i = 1, #hidden do
        local h = hidden[i]
        RemoveModelHide(h.position.x, h.position.y, h.position.z, 1.0, h.hash, false)
    end
end)
